services:
  mongodb-primary:
    image: mongo:7.0
    container_name: mongodb-primary
    restart: unless-stopped
    ports:
      - '27017:27017'
    command: mongod --replSet rs0 --bind_ip_all --noauth
    volumes:
      - mongodb_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - mongo-network

  mongo-init:
    image: mongo:7.0
    container_name: mongo-init
    restart: 'no'
    depends_on:
      - mongodb-primary
    volumes:
      - ./scripts/init-replica-set.sh:/init-replica-set.sh
    command: bash /init-replica-set.sh
    networks:
      - mongo-network

  mongo-express:
    image: mongo-express:1.0.0
    container_name: adonis_mongo_express
    restart: unless-stopped
    network_mode: host
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://localhost:27017/adonis_mongo
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    depends_on:
      - mongo-init

volumes:
  mongodb_data:

networks:
  mongo-network:
    driver: bridge
